backend:
  name: github
  repo: aslamsk/testig-new-blog
media_folder: posts
public_folder: assets
collections:
  - name: posts
    label: Blog
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }